site_name: Mi documentación de prácticas
site_url: https://Andreuuuuuu.github.io/Practicas/
theme:
  name: material  # Cambia aquí el nombre del tema
  language: es
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Inicio: index.md
  - Práctica 1: Col·laborant - pull request
  - Práctica 2: GIT - branques i unions
  - Práctica 3: Instal·lació d’un servidor LEMP
  - Práctica 4: MkDocs, Material i GitHub Pages
